import Head from "next/head";
import Navbar from "./Navbar";
import MobileNavbar from "./MobileNavbar";
import SpecializedSiteNavbar from "./SpecializedSiteNavbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <>
      {/* https://nextjs.org/docs/messages/no-document-title */}
      <Head>
        <title>Urban Cruise Ship</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="sm:max-w-screen-md lg:px-0 lg:max-w-screen-lg mx-auto relative">
        <div className="relative pr-2.5 z-10">
          <MobileNavbar />
        </div>
        <Navbar />
        <div className="relative z-0">
        <SpecializedSiteNavbar />
        </div>
        <div>{children}</div>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
