import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <>
      {/* https://nextjs.org/docs/messages/no-document-title */}
      <Head>
        <title>Urban Cruise Ship</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* https://tailwindcss.com/docs/installation/play-cdn
      this is a tempoary script for copy & pasting to Michael's code...
      ...in the final build, this will be deleted and we will use the command:
      $npm run build-css
      ...but for now, we will copy & paste the <script> tag below into each <head> tag
      that we send Michael for him to integrate into his build 
        <script src="https://cdn.tailwindcss.com"></script>*/}
      <div className="sm:max-w-screen-md lg:max-w-screen-lg mx-auto">
        <Navbar />
        <div className="page-content">{children}</div>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
