// https://youtu.be/rlcDpO_iDBU

import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/../images/ufavicon.ico" />
        <link href='https://fonts.cdnfonts.com/css/arial-rounded-mt-bold' rel='stylesheet' />
        <link href="https://fonts.cdnfonts.com/css/arial" rel="stylesheet" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
