import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://urbancruiseship.org/">Urban Cruise Ship</a>
        </h1>

        <div className="bg-yellow-300 m-2 p-2 text-amber-700 text-xl">
          Tailwind Styled Text
        </div>
        <Image src="/vercel.svg" height={230} width={230} />
        <Image src="/images/specialized-site-blocks/energy.svg" height={300} width={1000} />

      </main>
    </div>
  );
}
