import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const specializedSiteBlockHeight = 300;
  const specializedSiteBlockWidth = 510;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://urbancruiseship.org/">Urban Cruise Ship</a>
        </h1>

        <div className="grid grid-cols-3 gap-x-4">
          <Image
            src="/images/specialized-site-blocks/energy.svg"
            alt="Energy"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/matter.svg"
            alt="Matter"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/habitat.svg"
            alt="Habitat"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/cities.svg"
            alt="Cities"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/waste.svg"
            alt="Waste"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/oceans.svg"
            alt="Oceans"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/space.svg"
            alt="Space"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/costs.svg"
            alt="Costs"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
          <Image
            src="/images/specialized-site-blocks/history.svg"
            alt="History"
            height={specializedSiteBlockHeight}
            width={specializedSiteBlockWidth}
          />
        </div>
      </main>
    </div>
  );
}
