years=25
discount=0.08
bases=200
pv_array=15,000
batteries=1672500
waste_heat_recovery=50000
solar_hot_water=49530
steel_tank=21600
microgrid_cost=pv_array+batteries+waste_heat_recovery+solar_hot_water+steel_tank
baseline_fuel_costs=6071055
microgrid_fuel_costs=4117074
energy_fuel_savings=baseline_fuel_costs-microgrid_fuel_costs
baseline_emmissions_Brandon=.919500
baseline_emmissions_Vancouver=.788879
baseline_emmissions_Kanoya=.831462
baseline_emmissions_Churchill=1.036790
baseline_emmissions_Changi=.938783
average_baseline_emissions=(baseline_emmissions_Brandon+baseline_emmissions_Changi+baseline_emmissions_Churchill+baseline_emmissions_Kanoya+baseline_emmissions_Vancouver)/5
microgrid_emmissions_Brandon=.583270
microgrid_emmissions_Vancouver=.517335
microgrid_emmissions_Kanoya=.606460
microgrid_emmissions_Churchill=.636805
microgrid_emmissions_Changi=.743139
average_microgrid_emissions=(microgrid_emmissions_Brandon+microgrid_emmissions_Changi+microgrid_emmissions_Churchill+microgrid_emmissions_Kanoya+microgrid_emmissions_Vancouver)/5
emission_reductions=average_baseline_emissions-average_microgrid_emissions
social_cost_carbon=141.4
discount_factor=(sum([1.08 ** -i for i in range(25)]))

annual_cost=microgrid_cost/discount_factor
annual_fuel_savings=(baseline_fuel_costs-microgrid_fuel_costs)/discount_factor
annual_scc=social_cost_carbon*emission_reductions*1000000


